name: Test Windows Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello
        shell: cmd
        run: echo Hello from my Windows Self Hosted Runner

      - name: Show Current Directory
        shell: cmd
        run: cd

      - name: Show Git Version
        shell: cmd
        run: git --version

      - name: Show PATH
        shell: cmd
        run: echo %PATH%

      - name: Find Python
        shell: cmd
        run: where python

      - name: Show Python Version
        shell: cmd
        run: python --version
